version: '3.7'

services:
  scripts_etl:
    build:
      context: ./Scripts_ETL
      dockerfile: Dockerfile
    container_name: scripts_etl
    restart: no
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - ./Datalake:/usr/src/app/datalake
      - ./Warehouse_CSV:/usr/src/app/warehouse_csv
    depends_on:
      - warehouse_db

  warehouse_db:
    build:
      context: ./Warehouse_DB
      dockerfile: Dockerfile
    container_name: warehouse_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: